spring:
  datasource:
    url: jdbc:postgresql://dpg-cph19puct0pc73a27hmg-a.oregon-postgres.render.com/zaplivrosbd
    driver-class-name: org.postgresql.Driver
    username: zaplivros
    password: 9yWmvAcE9IoIk8E9jt44G05odfaF0jbp
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop # Atenção: Isto vai recriar o banco de dados a cada inicialização, o que pode não ser desejado em produção.
      generate-ddl: true

    sql:
        init:
            schema-locations: classpath:/schema-postgresql.sql
            mode: always
            platform: postgres
